version: "3.7"
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=rlence
      - POSTGRES_PASSWORD=rlencepassword

  back:
    container_name: back-app
    build: ./back
    image: node:16.16.0
    working_dir: /usr/local/app
    volumes:
      - ./back/:/usr/local/app
      - /usr/local/app/node_modules/
      - /usr/local/share/.cache/yarn/
    command: bash -c "yarn install && yarn start"
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - POSTGRES_USER=rlence
      - POSTGRES_PASSWORD=rlencepassword
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=postgres
      - NODE_ENV=development

  front:
    container_name: front-app
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - back
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn run dev"
    volumes:
      - ./front:/usr/src/app